### ISSUE TITLE
Add support for piped data

### ISSUE THREAD

**Issue by dimw** [dimw/mockbin-action#1]
Passing data via the pipe is a common case when coding in shell. Thus, it looks like a good idea to support checks for the piped data.

**Example interface:**

```yaml
- uses: 'dimw/mockbin-action@main'
  with:
    commands: kubectl
    assert-stdin: |
      apiVersion: v1
      kind: Secret
      metadata:
        name: my-secrets
        type: Opaque
      stringData:
        my-api-key: abcd1234
    assert-args: |
      ["apply", "-f", "-"]
```
**Expected behavior:**

The test should succeed when the data piped to `kubectl` is equal to the `assert-stdin` input, otherwise the test should fail.
